# Generated by Django 4.2.5 on 2023-09-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Содержание статьи')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('view_count', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована?')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена в базу')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('b_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsOrTails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='Результаты броска')),
                ('result_time', models.DateTimeField(auto_now_add=True, verbose_name='Время броска')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Текст комментария')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home2app.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home2app.author', verbose_name='Автор комментария')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home2app.author', verbose_name='Автор'),
        ),
    ]
